/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWanPollTaskRouteImport } from './routes/api.wan-poll-task'
import { Route as ApiWanCreateTaskRouteImport } from './routes/api.wan-create-task'
import { Route as ApiQwenGenerateImageRouteImport } from './routes/api.qwen-generate-image'
import { Route as ApiAnthropicGenerateRouteImport } from './routes/api.anthropic-generate'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWanPollTaskRoute = ApiWanPollTaskRouteImport.update({
  id: '/api/wan-poll-task',
  path: '/api/wan-poll-task',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWanCreateTaskRoute = ApiWanCreateTaskRouteImport.update({
  id: '/api/wan-create-task',
  path: '/api/wan-create-task',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQwenGenerateImageRoute = ApiQwenGenerateImageRouteImport.update({
  id: '/api/qwen-generate-image',
  path: '/api/qwen-generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnthropicGenerateRoute = ApiAnthropicGenerateRouteImport.update({
  id: '/api/anthropic-generate',
  path: '/api/anthropic-generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/api/anthropic-generate': typeof ApiAnthropicGenerateRoute
  '/api/qwen-generate-image': typeof ApiQwenGenerateImageRoute
  '/api/wan-create-task': typeof ApiWanCreateTaskRoute
  '/api/wan-poll-task': typeof ApiWanPollTaskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/api/anthropic-generate': typeof ApiAnthropicGenerateRoute
  '/api/qwen-generate-image': typeof ApiQwenGenerateImageRoute
  '/api/wan-create-task': typeof ApiWanCreateTaskRoute
  '/api/wan-poll-task': typeof ApiWanPollTaskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/api/anthropic-generate': typeof ApiAnthropicGenerateRoute
  '/api/qwen-generate-image': typeof ApiQwenGenerateImageRoute
  '/api/wan-create-task': typeof ApiWanCreateTaskRoute
  '/api/wan-poll-task': typeof ApiWanPollTaskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/api/anthropic-generate'
    | '/api/qwen-generate-image'
    | '/api/wan-create-task'
    | '/api/wan-poll-task'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/api/anthropic-generate'
    | '/api/qwen-generate-image'
    | '/api/wan-create-task'
    | '/api/wan-poll-task'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/api/anthropic-generate'
    | '/api/qwen-generate-image'
    | '/api/wan-create-task'
    | '/api/wan-poll-task'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ApiAnthropicGenerateRoute: typeof ApiAnthropicGenerateRoute
  ApiQwenGenerateImageRoute: typeof ApiQwenGenerateImageRoute
  ApiWanCreateTaskRoute: typeof ApiWanCreateTaskRoute
  ApiWanPollTaskRoute: typeof ApiWanPollTaskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wan-poll-task': {
      id: '/api/wan-poll-task'
      path: '/api/wan-poll-task'
      fullPath: '/api/wan-poll-task'
      preLoaderRoute: typeof ApiWanPollTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wan-create-task': {
      id: '/api/wan-create-task'
      path: '/api/wan-create-task'
      fullPath: '/api/wan-create-task'
      preLoaderRoute: typeof ApiWanCreateTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qwen-generate-image': {
      id: '/api/qwen-generate-image'
      path: '/api/qwen-generate-image'
      fullPath: '/api/qwen-generate-image'
      preLoaderRoute: typeof ApiQwenGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anthropic-generate': {
      id: '/api/anthropic-generate'
      path: '/api/anthropic-generate'
      fullPath: '/api/anthropic-generate'
      preLoaderRoute: typeof ApiAnthropicGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ApiAnthropicGenerateRoute: ApiAnthropicGenerateRoute,
  ApiQwenGenerateImageRoute: ApiQwenGenerateImageRoute,
  ApiWanCreateTaskRoute: ApiWanCreateTaskRoute,
  ApiWanPollTaskRoute: ApiWanPollTaskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
