/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VariationsRouteImport } from './routes/variations'
import { Route as UgcRouteImport } from './routes/ugc'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUgcGenerateRouteImport } from './routes/api.ugc-generate'
import { Route as ApiTranscribeAudioRouteImport } from './routes/api.transcribe-audio'
import { Route as ApiGenerateVariationsRouteImport } from './routes/api.generate-variations'
import { Route as ApiGenerateHiggsfieldPromptsRouteImport } from './routes/api.generate-higgsfield-prompts'
import { Route as ApiDetectProductRouteImport } from './routes/api.detect-product'
import { Route as ApiAnalyzeFramesRouteImport } from './routes/api.analyze-frames'

const VariationsRoute = VariationsRouteImport.update({
  id: '/variations',
  path: '/variations',
  getParentRoute: () => rootRouteImport,
} as any)
const UgcRoute = UgcRouteImport.update({
  id: '/ugc',
  path: '/ugc',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUgcGenerateRoute = ApiUgcGenerateRouteImport.update({
  id: '/api/ugc-generate',
  path: '/api/ugc-generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeAudioRoute = ApiTranscribeAudioRouteImport.update({
  id: '/api/transcribe-audio',
  path: '/api/transcribe-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateVariationsRoute = ApiGenerateVariationsRouteImport.update({
  id: '/api/generate-variations',
  path: '/api/generate-variations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateHiggsfieldPromptsRoute =
  ApiGenerateHiggsfieldPromptsRouteImport.update({
    id: '/api/generate-higgsfield-prompts',
    path: '/api/generate-higgsfield-prompts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDetectProductRoute = ApiDetectProductRouteImport.update({
  id: '/api/detect-product',
  path: '/api/detect-product',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeFramesRoute = ApiAnalyzeFramesRouteImport.update({
  id: '/api/analyze-frames',
  path: '/api/analyze-frames',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRoute
  '/ugc': typeof UgcRoute
  '/variations': typeof VariationsRoute
  '/api/analyze-frames': typeof ApiAnalyzeFramesRoute
  '/api/detect-product': typeof ApiDetectProductRoute
  '/api/generate-higgsfield-prompts': typeof ApiGenerateHiggsfieldPromptsRoute
  '/api/generate-variations': typeof ApiGenerateVariationsRoute
  '/api/transcribe-audio': typeof ApiTranscribeAudioRoute
  '/api/ugc-generate': typeof ApiUgcGenerateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRoute
  '/ugc': typeof UgcRoute
  '/variations': typeof VariationsRoute
  '/api/analyze-frames': typeof ApiAnalyzeFramesRoute
  '/api/detect-product': typeof ApiDetectProductRoute
  '/api/generate-higgsfield-prompts': typeof ApiGenerateHiggsfieldPromptsRoute
  '/api/generate-variations': typeof ApiGenerateVariationsRoute
  '/api/transcribe-audio': typeof ApiTranscribeAudioRoute
  '/api/ugc-generate': typeof ApiUgcGenerateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRoute
  '/ugc': typeof UgcRoute
  '/variations': typeof VariationsRoute
  '/api/analyze-frames': typeof ApiAnalyzeFramesRoute
  '/api/detect-product': typeof ApiDetectProductRoute
  '/api/generate-higgsfield-prompts': typeof ApiGenerateHiggsfieldPromptsRoute
  '/api/generate-variations': typeof ApiGenerateVariationsRoute
  '/api/transcribe-audio': typeof ApiTranscribeAudioRoute
  '/api/ugc-generate': typeof ApiUgcGenerateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/library'
    | '/projects'
    | '/ugc'
    | '/variations'
    | '/api/analyze-frames'
    | '/api/detect-product'
    | '/api/generate-higgsfield-prompts'
    | '/api/generate-variations'
    | '/api/transcribe-audio'
    | '/api/ugc-generate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/library'
    | '/projects'
    | '/ugc'
    | '/variations'
    | '/api/analyze-frames'
    | '/api/detect-product'
    | '/api/generate-higgsfield-prompts'
    | '/api/generate-variations'
    | '/api/transcribe-audio'
    | '/api/ugc-generate'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/library'
    | '/projects'
    | '/ugc'
    | '/variations'
    | '/api/analyze-frames'
    | '/api/detect-product'
    | '/api/generate-higgsfield-prompts'
    | '/api/generate-variations'
    | '/api/transcribe-audio'
    | '/api/ugc-generate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  LibraryRoute: typeof LibraryRoute
  ProjectsRoute: typeof ProjectsRoute
  UgcRoute: typeof UgcRoute
  VariationsRoute: typeof VariationsRoute
  ApiAnalyzeFramesRoute: typeof ApiAnalyzeFramesRoute
  ApiDetectProductRoute: typeof ApiDetectProductRoute
  ApiGenerateHiggsfieldPromptsRoute: typeof ApiGenerateHiggsfieldPromptsRoute
  ApiGenerateVariationsRoute: typeof ApiGenerateVariationsRoute
  ApiTranscribeAudioRoute: typeof ApiTranscribeAudioRoute
  ApiUgcGenerateRoute: typeof ApiUgcGenerateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/variations': {
      id: '/variations'
      path: '/variations'
      fullPath: '/variations'
      preLoaderRoute: typeof VariationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ugc': {
      id: '/ugc'
      path: '/ugc'
      fullPath: '/ugc'
      preLoaderRoute: typeof UgcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ugc-generate': {
      id: '/api/ugc-generate'
      path: '/api/ugc-generate'
      fullPath: '/api/ugc-generate'
      preLoaderRoute: typeof ApiUgcGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe-audio': {
      id: '/api/transcribe-audio'
      path: '/api/transcribe-audio'
      fullPath: '/api/transcribe-audio'
      preLoaderRoute: typeof ApiTranscribeAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-variations': {
      id: '/api/generate-variations'
      path: '/api/generate-variations'
      fullPath: '/api/generate-variations'
      preLoaderRoute: typeof ApiGenerateVariationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-higgsfield-prompts': {
      id: '/api/generate-higgsfield-prompts'
      path: '/api/generate-higgsfield-prompts'
      fullPath: '/api/generate-higgsfield-prompts'
      preLoaderRoute: typeof ApiGenerateHiggsfieldPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/detect-product': {
      id: '/api/detect-product'
      path: '/api/detect-product'
      fullPath: '/api/detect-product'
      preLoaderRoute: typeof ApiDetectProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-frames': {
      id: '/api/analyze-frames'
      path: '/api/analyze-frames'
      fullPath: '/api/analyze-frames'
      preLoaderRoute: typeof ApiAnalyzeFramesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  LibraryRoute: LibraryRoute,
  ProjectsRoute: ProjectsRoute,
  UgcRoute: UgcRoute,
  VariationsRoute: VariationsRoute,
  ApiAnalyzeFramesRoute: ApiAnalyzeFramesRoute,
  ApiDetectProductRoute: ApiDetectProductRoute,
  ApiGenerateHiggsfieldPromptsRoute: ApiGenerateHiggsfieldPromptsRoute,
  ApiGenerateVariationsRoute: ApiGenerateVariationsRoute,
  ApiTranscribeAudioRoute: ApiTranscribeAudioRoute,
  ApiUgcGenerateRoute: ApiUgcGenerateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
